- include_vars: "{{ item }}"
  with_items:
    - "zabbix_agent.yml"
    - "zabbix_proxy.yml"
    - "zabbix_server.yml"
    
- include: pkg-CentOs.yml
  when: ansible_os_family == "RedHat"

- include: pkg-Debian.yml
  when: ansible_os_family == "Debian"
