- include_vars: "{{ item }}"
  with_items:
    - "os_{{ ansible_os_family }}.yml"

- include: pkg-CentOs.yml
  when:
    - ansible_os_family == "RedHat"

- include: pkg-CentOs-agent.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_agent

- include: pkg-CentOs-proxy-sqlite3.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "sqlite3"

- include: pkg-CentOs-proxy-mysql.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "mysql"

- include: pkg-CentOs-proxy-pgsql.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "pgsql"

- include: pkg-CentOs-server-mysql.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_server
    - zabbix_server_db_type == "mysql"

- include: pkg-CentOs-server-pgsql.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_server
    - zabbix_server_db_type == "pgsql"

- include: pkg-CentOs-frontend.yml
  when:
    - ansible_os_family == "RedHat"
    - zabbix_install_frontend

- include: pkg-Debian.yml
  when:
    - ansible_os_family == "Debian"

- include: pkg-Debian-agent.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_agent

- include: pkg-Debian-proxy-sqlite3.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "sqlite3"

- include: pkg-Debian-proxy-mysql.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "mysql"

- include: pkg-Debian-proxy-pgsql.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_proxy
    - zabbix_proxy_db_type == "pgsql"

- include: pkg-Debian-server-mysql.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_server
    - zabbix_server_db_type == "mysql"

- include: pkg-Debian-server-pgsql.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_server
    - zabbix_server_db_type == "pgsql"


- include: pkg-Debian-frontend.yml
  when:
    - ansible_os_family == "Debian"
    - zabbix_install_frontend

- include: pkg-Windows-agent.yml
  when:
    - ansible_os_family == "Windows"

- include: configure-agent-Windows.yml
  when:
    - ansible_os_family == "Windows"
    - zabbix_install_agent

- include: configure-agent.yml
  when:
    - ansible_os_family != "Windows"
    - zabbix_install_agent

- include: configure-proxy.yml
  when:
    - ansible_os_family != "Windows"
    - zabbix_install_proxy

- include: configure-server.yml
  when:
    - ansible_os_family != "Windows"
    - zabbix_install_server

- include: configure-frontend.yml
  when:
    - ansible_os_family != "Windows"
    - zabbix_install_frontend
