---
- name: Zabbix | RedHat | General | Install Epel repository gpg key
  become: True
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Zabbix | RedHat | General | Install Epel repository
  become: True
  yum:
    name: epel-release
    state: latest

- name: Zabbix | RedHat | General | Make sure the ansible required dependencies are installed
  become: yes
  yum:
    name: python-pycurl
    state: present

- name: Zabbix | RedHat | General | Add the Zabbix repository
  become: yes
  yum:
    name: "http://repo.zabbix.com/zabbix/{{ zabbix_install_version }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_install_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Zabbix | RedHat | General | Install Zabbix repository gpg keys
  become: True
  rpm_key:
    state: present
    key: '{{ item }}'
  with_items:
    - '/etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591'
    - '/etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX'
