---
- name: Zabbix | Debian | Update apt cache with new zabbix agent versions
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Zabbix | Debian | Make sure Zabbix agent is installed
  become: yes
  apt:
    pkg: zabbix-agent
    state: latest
